# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutopia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='opus',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='piece',
            name='source',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
