# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutopia', '0002_auto_20160508_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='date_composed',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
