# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutopia', '0003_auto_20160509_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='lyricist',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
