# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutopia', '0004_auto_20160509_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
