# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutopia', '0006_auto_20160712_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='collections',
            field=models.ManyToManyField(to='mutopia.Collection'),
        ),
    ]
