# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutopia', '0007_piece_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='collections',
        ),
        migrations.AddField(
            model_name='collection',
            name='pieces',
            field=models.ManyToManyField(to='mutopia.Piece'),
        ),
    ]
