# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 17:17
from __future__ import unicode_literals

from django.db import migrations, models

def move_collection_pieces(apps, schema_editor):
    # data migration from deprecated CollectionPiece into the new m:m
    # relationship in Collection.
    CollectionPiece = apps.get_model('mutopia', 'CollectionPiece')
    for cp in CollectionPiece.objects.all():
        cp.collection.pieces.add(cp.piece)

class Migration(migrations.Migration):

    dependencies = [
        ('mutopia', '0008_auto_20160712_1713'),
    ]

    operations = [
        migrations.RunPython(move_collection_pieces),
    ]
