# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutopia', '0009_data_20160712_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpiece',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionpiece',
            name='piece',
        ),
        migrations.DeleteModel(
            name='CollectionPiece',
        ),
    ]
